### ISSUE TITLE
This fails under the latest sunpy...

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar_pysolar#41]
...needs to be updated to match with the latest API

**Comment by ayshih** [comment]
I haven't checked to see what API changes have affected your code, but let me know if you're having difficulty figuring anything out.

Also, with v0.8, SunPy's coordinate frames can now be transformed back and forth with Astropy's coordinate frames, and there is also a more accurate calculation of the position angle of the Sun (see https://github.com/sunpy/sunpy/pull/2186).  Leveraging the transform code may make your code cleaner, but I'm not positive about that since you want astrometric coordinates rather than apparent coordinates.

**Comment by ianan** [comment]
It seems to be two separate problems in making maps from NuSTAR data.

One is that mapmeta() no longer exists but I don't think this is a big deal as we can just remove the line
https://github.com/NuSTAR/nustar_pysolar/blob/1e782cc2457eb16a3d2921972a6f21e291a265cb/nustar_pysolar/map.py#L91
And use the dictionary/header directly in making the sunpy map.

The bigger issue is that the info you need to pass to make a working map has changed and not sure what it is we are missing now. I have the same problem with my code to make GOES/SXI maps in sunpy. There are warnings about there being more accurate ways of getting the solar ephemeris in v0.8 but I don't think that's it. I'm guessing something is missing and/or we don't have the units correct.

**Comment by bwgref** [comment]
@ayshih I think since we want to make sure that we also deal with the orbital parallax (which Astropy didn't used to do, but I haven't been following this lately) and make sure that we're doing *right* coordinate transformation, we'll probably stick with what we've got. I'm getting back into this again, so I'll take a look at what's been going on.

**Comment by ayshih** [comment]
Sorry, I've been distracted, but I finally spent some time looking into this.

Regarding `MapMeta`, yes, `sunpy.map.MapMeta` was renamed to `sunpy.util.MetaDict`, but as you noted, you can just supply the dictionary directly.

Regarding making a working map, I don't encounter any errors when running `make_sunpy()` or when plotting the Map object it creates.  I've tried it on both 0.8.x and the development branch with a random event file from the eclipse.  Maybe there's some library-version dependency that hasn't been captured?  Can you be more specific about the difficulties you're having?

Regarding coordinate transformations, I think you could actually account for orbital parallax using an "observer" attribute that we have in SunPy, but that will still be afflicted by the aberration correction by default.  Of course, there isn't really a reason for you to muck with your code that already works.

**Comment by bwgref** [comment]
Closed in PR #45
