### ISSUE TITLE
Major issue with Astropy v3.0.x with Sunpy

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar_pysolar#51]
Need to resolve this issue. Can't use with Astropy 3.0 as it stands now.

**Comment by ayshih** [comment]
Can you elaborate?  I'm not aware of any issue.

**Comment by bwgref** [comment]
Solved. User error on the configuration (I had an *old* version of Sunpy installed via a local installation rather than the most recent version installed via conda).
