### ISSUE TITLE
use_2to3 in setup.py invalid?

### ISSUE THREAD

**Issue by ianan** [NuSTAR/nustar_pysolar#64]
Installing on a fresh anaconda(python 3.9.7)/sunpy setup I was getting the error
`error in nustar_pysolar setup command: use_2to3 is invalid.`
after running `python setup.py install`.

Deleting [line 117 in setup.py ](https://github.com/NuSTAR/nustar_pysolar/blob/96e3150d5d156573ef61c660b519dffa7b171d24/setup.py#L117) `use_2to3=True,` fixed the issue and could install no problem.

**Comment by bwgref** [comment]
I haven't tested with python 3.9 yet...nor have I tested with astropy v4 (I think?). My setup.py for this is probably four years old, so it's probably way out of date.

**Comment by ianan** [comment]
I think it was actually with astropy v5... but a simple fix if others encounter the same issue on newer installs.

**Comment by bwgref** [comment]
Side note, at some point this whole package needs to be updated to the Astropy [APE 17](https://docs.astropy.org/projects/package-template/en/latest/ape17.html) installation without the use of astropy-helpers. I did this for nustar-gen-utils, but I never got around to it for nustar_pysolar.

**Comment by bwgref** [comment]
Should be deprecated now with #71
